name: Merge base branch into PRs

on:
  push:
    branches:
    # Automatically merge main/master branch into PR local branch.
      - main

jobs:
  merge:
    name: PR base merge
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
    - name: PR base merge
      uses: deliveryhero/pr-base-auto-merger@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Delay in seconds between consecutive merges
        MERGE_DELAY: 5
        # Label of PRs for which base can be merged. Use '*' to include all open PRs.
        MERGE_LABEL: 'auto-base-merge'
